# Generated by Django 2.0.3 on 2018-04-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_bids_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user',
        ),
        migrations.AlterField(
            model_name='bids',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.AppUser'),
        ),
    ]
