# Generated by Django 2.0.3 on 2018-04-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_auto_20180413_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='user',
        ),
    ]
